global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gearshare-api
    static_configs:
      - targets: ["api:8080"]

  - job_name: gearshare-notification-service
    static_configs:
      - targets: ["notification-service:9101"]

  - job_name: gearshare-search-indexer
    static_configs:
      - targets: ["search-indexer:9102"]
